const products = [
  {
    image: "pineapple.jpg",
    name: "pineapple",
    category: "Fruits",
    price: 200,
    id: 1,
  },
  {
    image: "apple.jpg",
    description: "Fresh looking apple",
    name: " apple",
    category: "Fruits",
    price: 100,
    id: 2,
  },
  {
    image: "apricot.jpg",
    name: "apricot",
    category: "Fruits",
    price: 120,
    id: 3,
    description: "A nice ripe fruit",
  },
  {
    image: "banana fresh.jpg",
    name: "banana",
    category: "Fruits",
    price: 135,
    id: 4,
    description: "A nice ripe fruit",
  },
  {
    image: "carolina.jpg",
    name: "Carolina Rice",
    category: "Rice",
    price: 120,
    id: 5,
    description: "Rice",
  },
  {
    image: "onions.jpg",
    name: "onions",
    category: "veggies",
    price: 90,
    id: 6,
    description: "onions",
  },
  {
    image: "cucumber.jpg",
    name: "cucumber",
    category: "veggies",
    price: 70,
    id: 7,
    description: " fres cucumber",
  },
  {
    image: "cabbage.jpg",
    name: "cabbage",
    category: "veggies",
    price: 160,
    id: 8,
    description: "fresh cabbage",
  },
  {
    image: "berries.jpg",
    name: "berries",
    category: "Fruits",
    price: 140,
    id: 9,
    description: "sweet berries",
  },
  {
    image: "burger-fries.jpg",
    name: "burger & fries",
    category: "burger",
    price: 50,
    id: 10,
    description: "tasty burger",
  },
  {
    image: "c-cake.jpg",
    name: "chocolate cake",
    category: "cake",
    price: 50,
    id: 11,
    description: "tasty cake",
  },
  {
    image: "cocolate icecream.jpg",
    name: "chocolate ice-cream",
    category: "ice-cream",
    price: 20,
    id: 12,
    description: "sweet ice-cream",
  },
  {
    image: "cupcake.jpg",
    name: "cupcake",
    category: "cake",
    price:10,
    id: 13,
    description: "tasty cake",
  },
  {
    image: "e-plant.jpg",
    name: "egg plant",
    category: "veggies",
    price: 40,
    id: 14,
    description: "fresh eggplant",
  },
  {
    image: "broccoli.jpg",
    name: "broccoli",
    category: "veggies",
    price: 100,
    id: 15,
    description: "fresh broccoli",
  },
  {
    image: "ginger.jpg",
    name: "ginger",
    category: "veggies",
    price: 170,
    id: 16,
    description: "fresh ginger",
  },
  {
    image: "potato.jpg",
    name: "potato",
    category: "veggies",
    price: 80,
    id: 17,
    description: "potatoes",
  },
  {
    image: "lettuce.jpg",
    name: "lettuce",
    category: "veggies",
    price: 40,
    id: 18,
    description: "fresh veggies",
  },
  {
    image: "tomato.jpg",
    name: "tomato",
    category: "veggies",
    price: 100,
    id: 19,
    description: "fresh tomatoes",
  },
  
];

export default products;
